name: Action CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Update Mappings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Install Build Tool
        run: pnpm i -g @vercel/ncc
      - name: Build
        run: pnpm run build
      - name: Update Mappings
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[skip ci] Update mappings'
          file_pattern: 'dist/*.js dist/*.js.map dist/*.cjs'
          commit_user_name: r2-action-bot[bot]
          commit_user_email: 118486773+r2-action-bot[bot]@users.noreply.github.com
          commit_author: r2-action-bot[bot] <118486773+r2-action-bot[bot]@users.noreply.github.com>
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.2.3
